title : "包丁一本さらしに巻いて"
description: "Python + Data"
url: https://akirachiku.com
tagline: 
author :
  name : Akira Chiku
  email : akira.chiku@gmail.com
  github : achiku
  twitter : _achiku

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: rouge
markdown: kramdown

production_url : https://akirachiku.com
comments : True

source:      .
excerpt_separator: "。"
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
exclude:     []
gems:        []
timezone:    nil
encoding:    nil

future:      true
show_drafts: nil
limit_posts: 0

permalink:     date
paginate_path: 'page:num'
