title : "包丁一本さらしに巻いて"
description: "Python + Data"
url: http://achiku.github.io
tagline: 
author :
  name : Akira Chiku
  email : akira.chiku@gmail.com
  github : achiku
  twitter : _achiku

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments
markdown: redcarpet

production_url : http://achiku.github.io
comments : True

source:      .
excerpt_separator: "。"
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
gems:        []
timezone:    nil
encoding:    nil

future:      true
show_drafts: nil
limit_posts: 0

relative_permalinks: true

permalink:     date
paginate_path: 'page:num'

JB :
  version : 0.2.13
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

   
  # Settings for analytics helper
  # Set 'provider' to the analytics provider you want to use.
  # Set 'provider' to false to turn analytics off globally.
  #        
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-123-12'
    getclicky :
      site_id : 
    mixpanel :
        token : '_MIXPANEL_TOKEN_'

  # Settings for sharing 
  # Sharing is for things like tweet, plusone, hn upvotes, like, linkedin
  # Add a tweet button 		=> provider : tweet
  # Add a like button 		=> provider : like (you also need a facebook appid)
  # Add a plus one button 	=> provider : plusone
  # Add a HN button 		=> provider : hn
  # Add them all (i.e. hn + tweet + plusone + like) => provider : all
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : tweet
    twitter :
      size :
      via :
      count :
    facebook :
      appid : 205602882797935
      layout : button_count
      font :
      faces : false
      width : 90
    googleplus :
      size : medium
      width :
      annotation : bubble
    linkedin :
      counter : right
    
  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"   
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.
